### ISSUE TITLE
RobColeLr GitHub Organization

### ISSUE THREAD

**Issue by ickc** [atramos/RawPlusJpeg#1]
Hi, I opened a GitHub Organization named as RobColeLr. I think What you did is great and may be it's time to have an organization that gathered everything he offered that we can redistribute. I already invited you and see if you're interested in transferring this repo under that umbrella (I can invite you as owner if you want).

I don't have much plan for it (e.g. I probably won't be looking into the code and start modifying it). But if the project gains traction, at least it would be a one-stop-shop for his legacy. And who knows, may be some developers would even start to continue from his legacy.

**Comment by atramos** [comment]
Done! I have moved my repository to your org
